---
stages:
  - cleanup
  - prepare
  - build
  - test
  - push

variables:
  CI_URL: "${CI_REGISTRY}/messtechnik-labor/docker"
  LINT_IMAGE: "${CI_URL}/lint:latest"
  LABEL: "maintainer=messtechnik-labor"

default:
  tags: [x86_64]
  retry: 2

# cleanup

.template_cleanup:
  rules:
    - if: "$CI_COMMIT_TAG"
  stage: cleanup
  image: docker:dind-rootless
  needs: []
  script:
    - df -H
    - docker system prune -a -f --filter "until=72h" --filter "label=${LABEL}"

amd_cleanup:
  extends: .template_cleanup

arm_cleanup:
  tags: [aarch64]
  image: "${ARM_CI_IMAGE}"
  extends: .template_cleanup

# prepare

lint:
  stage: prepare
  image: ${LINT_IMAGE}
  rules:
    - if: "$CI_COMMIT_TAG"
  needs: []
  script:
    - lint

# build

build:
  stage: build
  needs: ["lint"]
  image: docker:dind-rootless
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - docker buildx create --use
    - |
      docker buildx build \
      -t "${CI_REGISTRY_IMAGE}/tmp:${CI_COMMIT_TAG}" \
      --platform linux/amd64,linux/arm64/v8 \
      --file Dockerfile \
      --push .

# test

.template_test:
  stage: test
  rules:
    - if: "$CI_COMMIT_TAG"
  before_script: []
  needs: [build]
  image:
    name: "${CI_REGISTRY_IMAGE}/tmp:${CI_COMMIT_TAG}"
    entrypoint: [""]
  script:
    - pytest

amd_test:
  extends: .template_test

arm_test:
  extends: .template_test
  tags: [aarch64]

# push

push:
  needs: ["amd_test", "arm_test"]
  rules:
    - if: "$CI_COMMIT_TAG"
  stage: push
  image: docker:dind-rootless
  script:
    - tmp_image="${CI_REGISTRY_IMAGE}/tmp:${CI_COMMIT_TAG}"
    - docker pull "$tmp_image"
    - docker tag "$tmp_image" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - docker tag "$tmp_image" "${CI_REGISTRY_IMAGE}:latest"
    - docker push --all-tags "${CI_REGISTRY_IMAGE}"
