---
stages:
  - static-analysis
  - build
  - test
  - push

variables:
  LINT_IMAGE: "${CI_REGISTRY}/messtechnik-labor/docker/lint:latest"
  LABEL: "maintainer=messtechnik-labor"

default:
  tags: [x86_64]
  retry: 2

.template_docker:
  image: docker:dind
  rules:
    - if: "$CI_COMMIT_TAG"
  before_script:
    - df -h
    - docker system prune -a -f --filter "until=72h" --filter "label=${LABEL}"
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

# prepare

lint:
  image: ${LINT_IMAGE}
  needs: []
  rules:
    - if: "$CI_COMMIT_TAG"
  stage: static-analysis
  script:
    - ls -la
    - lint

# build

build:
  extends: .template_docker
  needs: [lint]
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - |
      docker buildx create  \
      --use \
      --platform linux/amd64,linux/arm64/v8 \
    - |
      docker buildx build \
      -t "${CI_REGISTRY_IMAGE}/tmp:${CI_COMMIT_TAG}" \
      --label "${LABEL}" \
      --provenance false \
      --platform linux/amd64,linux/arm64/v8 \
      --file Dockerfile \
      --push .
    - docker buildx rm --force

# test

.template_test:
  image:
    name: "${CI_REGISTRY_IMAGE}/tmp:${CI_COMMIT_TAG}"
    entrypoint: [""]
  needs: [build]
  rules:
    - if: "$CI_COMMIT_TAG"
  stage: test
  script:
    - pwd
    - ls -la
    - pytest

amd_test:
  extends: .template_test

arm_test:
  extends: .template_test
  tags: [aarch64]

# push

push:
  extends: .template_docker
  needs: ["amd_test", "arm_test"]
  stage: push
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - tmp_image="${CI_REGISTRY_IMAGE}/tmp:${CI_COMMIT_TAG}"
    - docker pull "$tmp_image"
    - docker tag "$tmp_image" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - docker tag "$tmp_image" "${CI_REGISTRY_IMAGE}:latest"
    - docker push --all-tags "${CI_REGISTRY_IMAGE}"
